#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=install_env
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=slurm_outputs/install_env%A.out

module purge
module load 2023
module load CUDA/12.1.1

# Your job starts in the directory where you call sbatch
cd ../../..

conda create --name instdiff python=3.8 -y
conda activate instdiff

pip install -r requirements.txt